name = "enc-gofundme-scraper"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "GFM_DATA"
id = "REPLACE_AFTER_WRANGLER_KV_CREATE"
